# Generated by Django 5.x

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocalizationJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_group_key", models.CharField(db_index=True, default="", max_length=64)),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("source_text", models.TextField(blank=True)),
                ("source_language", models.CharField(default="en", max_length=32)),
                ("target_language", models.CharField(default="en", max_length=32)),
                ("target_region", models.CharField(default="global", max_length=64)),
                ("tone", models.CharField(default="neutral", max_length=32)),
                ("audience", models.CharField(default="general", max_length=64)),
                ("preserve_intent", models.BooleanField(default=True)),
                ("preserve_sentiment", models.BooleanField(default=True)),
                ("use_ocr", models.BooleanField(default=True)),
                ("ocr_text", models.TextField(blank=True)),
                ("sentiment_label", models.CharField(blank=True, max_length=32)),
                ("sentiment_score", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ("cultural_risk_score", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ("explanation", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="localizationjob",
            index=models.Index(fields=["version_group_key", "version_number"], name="localizatio_version_8d2a08_idx"),
        ),
        migrations.AddIndex(
            model_name="localizationjob",
            index=models.Index(fields=["created_at"], name="localizatio_created_70f86f_idx"),
        ),
        migrations.AddIndex(
            model_name="localizationjob",
            index=models.Index(fields=["source_language", "target_language", "created_at"], name="localizatio_source__1a10e0_idx"),
        ),
        migrations.CreateModel(
            name="LocalizationVariation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("variant_name", models.CharField(max_length=32)),
                ("localized_text", models.TextField()),
                ("explanation", models.JSONField(blank=True, default=list)),
                ("cultural_risk_score", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variations", to="localization.localizationjob"),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("job", "variant_name")},
            },
        ),
        migrations.AddIndex(
            model_name="localizationvariation",
            index=models.Index(fields=["job", "variant_name"], name="localizatio_job_id_3150f6_idx"),
        ),
        migrations.AddIndex(
            model_name="localizationvariation",
            index=models.Index(fields=["created_at"], name="localizatio_created_33d8fd_idx"),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("liked", models.BooleanField(default=True)),
                ("source_channel", models.CharField(default="web", max_length=32)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feedback_entries", to="localization.localizationjob"),
                ),
                (
                    "variation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feedback_entries", to="localization.localizationvariation"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["job", "created_at"], name="localizatio_job_id_3d713c_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["variation", "created_at"], name="localizatio_variati_a8e163_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["liked", "created_at"], name="localizatio_liked_73d580_idx"),
        ),
    ]
