# Generated by Django 5.2.12 on 2026-04-09 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("localization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="feedback",
            new_name="localizatio_job_id_2ce0bb_idx",
            old_name="localizatio_job_id_3d713c_idx",
        ),
        migrations.RenameIndex(
            model_name="feedback",
            new_name="localizatio_variati_548d64_idx",
            old_name="localizatio_variati_a8e163_idx",
        ),
        migrations.RenameIndex(
            model_name="feedback",
            new_name="localizatio_liked_f73e7a_idx",
            old_name="localizatio_liked_73d580_idx",
        ),
        migrations.RenameIndex(
            model_name="localizationjob",
            new_name="localizatio_version_03b059_idx",
            old_name="localizatio_version_8d2a08_idx",
        ),
        migrations.RenameIndex(
            model_name="localizationjob",
            new_name="localizatio_created_a0cfcd_idx",
            old_name="localizatio_created_70f86f_idx",
        ),
        migrations.RenameIndex(
            model_name="localizationjob",
            new_name="localizatio_source__eed1a0_idx",
            old_name="localizatio_source__1a10e0_idx",
        ),
        migrations.RenameIndex(
            model_name="localizationvariation",
            new_name="localizatio_job_id_13b56d_idx",
            old_name="localizatio_job_id_3150f6_idx",
        ),
        migrations.RenameIndex(
            model_name="localizationvariation",
            new_name="localizatio_created_54dfe5_idx",
            old_name="localizatio_created_33d8fd_idx",
        ),
        migrations.AddField(
            model_name="localizationjob",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="localization_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
